In [ ]:
import pandas as pd
import numpy as np 
df = pd.read_csv("Mutual Fund Dataset 2025.csv")
df.head(5)

,Funds,Fund Manager,Category,RupeeVestRating,AUM(in Rs. cr),ExpenseRatio (%),Fund Type,Inception Date,Benchmark Index,NAV,...,Avg. Maturity(in yrs),Mod. Duration(in yrs),Yield To Maturity (%),Alpha,Sharpe,Sortino,Beta,Standard Deviation,classification,Exit_load_Remarks
0,360 ONE Balanced Hybrid Fund-Reg(G),Mayur Patel,HY-EQ,Unrated,860.1,1.94,Open Ended,25-Sep-23,NIFTY 50 Hybrid Composite Debt 50:50 Index,12.45,...,2.93,-,7.39,8.27,1.58,2.28,1.2,7.5,Hybrid : Equity Oriented,Nil upto 10% of units and 1% for remaining uni...
1,360 ONE Dynamic Bond Fund-Reg(G),Milan Mody,DT-DYN,2,737.5,0.52,Open Ended,24-Jun-13,CRISIL Dynamic Bond Index,21.5,...,6.85,-,7.35,3.5,3.72,6.7,0.64,1.45,Debt : Dynamic Bond,Nil
2,360 ONE ELSS Tax Saver Nifty 50 Index Fund-Reg(G),Parijat Garg,EQ-ELSS,Unrated,75.8,0.52,Open Ended,28-Dec-22,NIFTY 50 - TRI,13.45,...,-,-,-,1.51,0.47,0.71,0.99,13.9,Equity : Tax Saving (ELSS),Nil
3,360 ONE Flexicap Fund-Reg(G),Mayur Patel,EQ-FLEX,Unrated,1254.2,2.08,Open Ended,30-Jun-23,BSE 500 - TRI,15.33,...,-,-,-,16.98,1.4,2.02,0.92,15.45,Equity : Flexi Cap,1% on or before 365D Nil after 365D
4,360 ONE Focused Equity Fund-Reg(G),Mayur Patel,EQ-MLC,4,7305,1.78,Open Ended,30-Oct-14,BSE 500 - TRI,46.19,...,-,-,-,6.25,0.71,1,1.02,16.03,Equity : Multi Cap,1% on or before 12M

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 37 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Funds                       1797 non-null   object
 1   Fund Manager                1797 non-null   object
 2   Category                    1797 non-null   object
 3   RupeeVestRating             1797 non-null   object
 4   AUM(in Rs. cr)              1797 non-null   object
 5   ExpenseRatio (%)            1797 non-null   object
 6   Fund Type                   1797 non-null   object
 7   Inception Date              1797 non-null   object
 8   Benchmark Index             1796 non-null   object
 9    NAV                        1797 non-null   object
 10   52 WeekHigh (NAV)          1797 non-null   object
 11   52 WeekLow (NAV)           1797 non-null   object
 12  Return (%)1 mo              1797 non-null   object
 13  Return (%)3 mo              1797 non-null   object
 14  Return (%)6 mo              1797 non-null   object
 15  Return (%)1 yr              1797 non-null   object
 16  Return (%)2 yrs             1797 non-null   object
 17  Return (%)3 yrs             1797 non-null   object
 18  Return (%)5 yrs             1797 non-null   object
 19  Return (%)10 yrs            1797 non-null   object
 20  Turnover Ratio (%)          1797 non-null   object
 21   No. ofStocks               1797 non-null   object
 22  Avg. Market Cap(in Rs. cr)  1797 non-null   object
 23  Large Cap(%)                1797 non-null   object
 24  Mid Cap(%)                  1797 non-null   object
 25  Small Cap(%)                1797 non-null   object
 26  Highest Sector              1797 non-null   object
 27  Avg. Maturity(in yrs)       1797 non-null   object
 28  Mod. Duration(in yrs)       1797 non-null   object
 29  Yield To Maturity (%)       1797 non-null   object
 30  Alpha                       1797 non-null   object
 31  Sharpe                      1797 non-null   object
 32  Sortino                     1797 non-null   object
 33  Beta                        1797 non-null   object
 34  Standard Deviation          1797 non-null   object
 35  classification              1797 non-null   object
 36  Exit_load_Remarks           1504 non-null   object
dtypes: object(37)
memory usage: 519.6+ KB

In [97]:
df_1 = df

In [98]:
df_1.loc[df_1["Mod. Duration(in yrs)"]=='-',"Mod. Duration(in yrs)"] = np.nan
df_1.loc[df_1["Avg. Maturity(in yrs)"]=='-',"Avg. Maturity(in yrs)"] = np.nan

In [99]:
df_1[["Avg. Maturity(in yrs)","Mod. Duration(in yrs)"]]

     Avg. Maturity(in yrs) Mod. Duration(in yrs)
0                     2.93                   NaN
1                     6.85                   NaN
2                      NaN                   NaN
3                      NaN                   NaN
4                      NaN                   NaN
...                    ...                   ...
1792                  0.44                   0.4
1793                   NaN                   NaN
1794                   NaN                   NaN
1795                  0.01                   NaN
1796                   NaN                   NaN

[1797 rows x 2 columns]

In [100]:
df_1.loc[df_1["RupeeVestRating"]=='Unrated',"RupeeVestRating"] = None

In [101]:
df_1.columns = (df_1.columns
                .str.strip()
                .str.replace(r"[()%]","",regex = True)
                .str.replace(r"\s+","_",regex=True)
                .str.replace(r"\.","",regex=True))

In [102]:
df_1.head()

,Funds,Fund_Manager,Category,RupeeVestRating,AUMin_Rs_cr,ExpenseRatio_,Fund_Type,Inception_Date,Benchmark_Index,NAV,...,Avg_Maturityin_yrs,Mod_Durationin_yrs,Yield_To_Maturity_,Alpha,Sharpe,Sortino,Beta,Standard_Deviation,classification,Exit_load_Remarks
0,360 ONE Balanced Hybrid Fund-Reg(G),Mayur Patel,HY-EQ,None,860.1,1.94,Open Ended,25-Sep-23,NIFTY 50 Hybrid Composite Debt 50:50 Index,12.45,...,2.93,NaN,7.39,8.27,1.58,2.28,1.2,7.5,Hybrid : Equity Oriented,Nil upto 10% of units and 1% for remaining uni...
1,360 ONE Dynamic Bond Fund-Reg(G),Milan Mody,DT-DYN,2,737.5,0.52,Open Ended,24-Jun-13,CRISIL Dynamic Bond Index,21.5,...,6.85,NaN,7.35,3.5,3.72,6.7,0.64,1.45,Debt : Dynamic Bond,Nil
2,360 ONE ELSS Tax Saver Nifty 50 Index Fund-Reg(G),Parijat Garg,EQ-ELSS,None,75.8,0.52,Open Ended,28-Dec-22,NIFTY 50 - TRI,13.45,...,NaN,NaN,-,1.51,0.47,0.71,0.99,13.9,Equity : Tax Saving (ELSS),Nil
3,360 ONE Flexicap Fund-Reg(G),Mayur Patel,EQ-FLEX,None,1254.2,2.08,Open Ended,30-Jun-23,BSE 500 - TRI,15.33,...,NaN,NaN,-,16.98,1.4,2.02,0.92,15.45,Equity : Flexi Cap,1% on or before 365D Nil after 365D
4,360 ONE Focused Equity Fund-Reg(G),Mayur Patel,EQ-MLC,4,7305,1.78,Open Ended,30-Oct-14,BSE 500 - TRI,46.19,...,NaN,NaN,-,6.25,0.71,1,1.02,16.03,Equity : Multi Cap,1% on or before 12M

In [103]:
rename_dict = {
    "AUMin_Rs_cr":"AUM_Cr",
    "ExpenseRatio_":"Expense_Ratio",
    "Return_1_mo": "Return_1M",
    "Return_3_mo": "Return_3M",
    "Return_6_mo": "Return_6M",
    "Return_1_yr": "Return_1Y",
    "Return_2_yrs": "Return_2Y",
    "Return_3_yrs": "Return_3Y",
    "Return_5_yrs": "Return_5Y",
    "Return_10_yrs": "Return_10Y",
    "Avg_Market_Capin_Rs_cr": "Avg_MarketCap_Cr",
    "Avg_Maturityin_yrs": "Avg_Maturity_Yrs",
    "Mod_Durationin_yrs": "Mod_Duration_Yrs",
    "Yield_To_Maturity_": "YTM"
}

df_1.rename(columns=rename_dict, inplace=True)
df_1.head()

,Funds,Fund_Manager,Category,RupeeVestRating,AUM_Cr,Expense_Ratio,Fund_Type,Inception_Date,Benchmark_Index,NAV,...,Avg_Maturity_Yrs,Mod_Duration_Yrs,YTM,Alpha,Sharpe,Sortino,Beta,Standard_Deviation,classification,Exit_load_Remarks
0,360 ONE Balanced Hybrid Fund-Reg(G),Mayur Patel,HY-EQ,None,860.1,1.94,Open Ended,25-Sep-23,NIFTY 50 Hybrid Composite Debt 50:50 Index,12.45,...,2.93,NaN,7.39,8.27,1.58,2.28,1.2,7.5,Hybrid : Equity Oriented,Nil upto 10% of units and 1% for remaining uni...
1,360 ONE Dynamic Bond Fund-Reg(G),Milan Mody,DT-DYN,2,737.5,0.52,Open Ended,24-Jun-13,CRISIL Dynamic Bond Index,21.5,...,6.85,NaN,7.35,3.5,3.72,6.7,0.64,1.45,Debt : Dynamic Bond,Nil
2,360 ONE ELSS Tax Saver Nifty 50 Index Fund-Reg(G),Parijat Garg,EQ-ELSS,None,75.8,0.52,Open Ended,28-Dec-22,NIFTY 50 - TRI,13.45,...,NaN,NaN,-,1.51,0.47,0.71,0.99,13.9,Equity : Tax Saving (ELSS),Nil
3,360 ONE Flexicap Fund-Reg(G),Mayur Patel,EQ-FLEX,None,1254.2,2.08,Open Ended,30-Jun-23,BSE 500 - TRI,15.33,...,NaN,NaN,-,16.98,1.4,2.02,0.92,15.45,Equity : Flexi Cap,1% on or before 365D Nil after 365D
4,360 ONE Focused Equity Fund-Reg(G),Mayur Patel,EQ-MLC,4,7305,1.78,Open Ended,30-Oct-14,BSE 500 - TRI,46.19,...,NaN,NaN,-,6.25,0.71,1,1.02,16.03,Equity : Multi Cap,1% on or before 12M

In [104]:
numcols = ["AUM_Cr", "Expense_Ratio", "NAV", "52_WeekHigh_NAV", "52_WeekLow_NAV",
            "Return_1M", "Return_3M", "Return_6M", "Return_1Y", "Return_2Y",
            "Return_3Y", "Return_5Y", "Return_10Y", 
            "Avg_Maturity_Yrs", "Mod_Duration_Yrs", "YTM"]
for col in numcols:
    df_1[col] = (df_1[col]
               .astype(str)
               .replace("-",np.nan)
               .replace("nan",np.nan)
               .astype(float))
df_1["Inception_Date"] = pd.to_datetime(
    df_1["Inception_Date"].replace(["-", "--", "N/A", "Na", "na", ""], pd.NA),
    errors="coerce"
)

C:\Users\Sinha\AppData\Local\Temp\ipykernel_26472\2555908778.py:11: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

In [105]:
df_1.head()

,Funds,Fund_Manager,Category,RupeeVestRating,AUM_Cr,Expense_Ratio,Fund_Type,Inception_Date,Benchmark_Index,NAV,...,Avg_Maturity_Yrs,Mod_Duration_Yrs,YTM,Alpha,Sharpe,Sortino,Beta,Standard_Deviation,classification,Exit_load_Remarks
0,360 ONE Balanced Hybrid Fund-Reg(G),Mayur Patel,HY-EQ,None,860.1,1.94,Open Ended,2023-09-25,NIFTY 50 Hybrid Composite Debt 50:50 Index,12.45,...,2.93,NaN,7.39,8.27,1.58,2.28,1.2,7.5,Hybrid : Equity Oriented,Nil upto 10% of units and 1% for remaining uni...
1,360 ONE Dynamic Bond Fund-Reg(G),Milan Mody,DT-DYN,2,737.5,0.52,Open Ended,2013-06-24,CRISIL Dynamic Bond Index,21.50,...,6.85,NaN,7.35,3.5,3.72,6.7,0.64,1.45,Debt : Dynamic Bond,Nil
2,360 ONE ELSS Tax Saver Nifty 50 Index Fund-Reg(G),Parijat Garg,EQ-ELSS,None,75.8,0.52,Open Ended,2022-12-28,NIFTY 50 - TRI,13.45,...,NaN,NaN,NaN,1.51,0.47,0.71,0.99,13.9,Equity : Tax Saving (ELSS),Nil
3,360 ONE Flexicap Fund-Reg(G),Mayur Patel,EQ-FLEX,None,1254.2,2.08,Open Ended,2023-06-30,BSE 500 - TRI,15.33,...,NaN,NaN,NaN,16.98,1.4,2.02,0.92,15.45,Equity : Flexi Cap,1% on or before 365D Nil after 365D
4,360 ONE Focused Equity Fund-Reg(G),Mayur Patel,EQ-MLC,4,7305.0,1.78,Open Ended,2014-10-30,BSE 500 - TRI,46.19,...,NaN,NaN,NaN,6.25,0.71,1,1.02,16.03,Equity : Multi Cap,1% on or before 12M

In [106]:
print(df_1.dtypes)

Funds                         object
Fund_Manager                  object
Category                      object
RupeeVestRating               object
AUM_Cr                       float64
Expense_Ratio                float64
Fund_Type                     object
Inception_Date        datetime64[ns]
Benchmark_Index               object
NAV                          float64
52_WeekHigh_NAV              float64
52_WeekLow_NAV               float64
Return_1M                    float64
Return_3M                    float64
Return_6M                    float64
Return_1Y                    float64
Return_2Y                    float64
Return_3Y                    float64
Return_5Y                    float64
Return_10Y                   float64
Turnover_Ratio_               object
No_ofStocks                   object
Avg_MarketCap_Cr              object
Large_Cap                     object
Mid_Cap                       object
Small_Cap                     object
Highest_Sector                object
Avg_Maturity_Yrs             float64
Mod_Duration_Yrs             float64
YTM                          float64
Alpha                         object
Sharpe                        object
Sortino                       object
Beta                          object
Standard_Deviation            object
classification                object
Exit_load_Remarks             object
dtype: object

In [107]:
df_2 = df_1

In [108]:
df_1["Inception_Date"] = pd.to_datetime(df_1["Inception_Date"], format="%d-%b-%Y", errors="coerce")

In [109]:
df_2["Fund_Age_Years"] = round((pd.Timestamp.today() - df_1["Inception_Date"]).dt.days / 365,2)
df_2["Fund_Age_Years"]

0        2.06
1       12.32
2        2.80
3        2.30
4       10.97
        ...
1792     6.37
1793     1.64
1794     1.35
1795     1.75
1796     1.35
Name: Fund_Age_Years, Length: 1797, dtype: float64

In [110]:

df_1["Return_1Y_vs_2Y"] = round((df_1["Return_1Y"] / df_1["Return_2Y"]),2)
df_1["Return_2Y_vs_3Y"] = round((df_1["Return_2Y"] / df_1["Return_3Y"]),2)
df_2["Return_1Y_vs_3Y"] = round((df_2["Return_1Y"] / df_2["Return_3Y"]),2)
df_2["Return_3Y_vs_5Y"] = round((df_2["Return_3Y"] / df_2["Return_5Y"]),2)

In [111]:
df_2[["Return_1Y_vs_3Y","Return_3Y_vs_5Y"]]

      Return_1Y_vs_3Y  Return_3Y_vs_5Y
0                 NaN              NaN
1                1.46             0.99
2                 NaN              NaN
3                 NaN              NaN
4                1.03             0.72
...               ...              ...
1792             1.20             1.16
1793              NaN              NaN
1794              NaN              NaN
1795              NaN              NaN
1796              NaN              NaN

[1797 rows x 2 columns]

In [112]:
return_cols = ["Return_1Y","Return_2Y","Return_3Y","Return_5Y","Return_10Y"]
df_2["Avg_Return"] = df_2[return_cols].mean(axis=1).round(2)

In [113]:
df_2["Avg_Return"].head(20)

0     16.18
1      7.57
2     12.84
3     27.02
4     17.61
5      6.29
6     26.18
7      6.80
8      6.43
9     15.55
10    14.81
11    12.51
12    12.95
13     7.06
14      NaN
15    13.27
16    17.53
17      NaN
18     7.57
19     9.60
Name: Avg_Return, dtype: float64

In [114]:
# Volatility Proxy (NAV Range %) -> high % range -> more volatile fund.
df_2["NAV_Range_%"] = (
    (df_2["52_WeekHigh_NAV"] - df_2["52_WeekLow_NAV"]) / df_2["52_WeekLow_NAV"] * 100
).round(2)

In [115]:
df.head()

,Funds,Fund_Manager,Category,RupeeVestRating,AUM_Cr,Expense_Ratio,Fund_Type,Inception_Date,Benchmark_Index,NAV,...,Standard_Deviation,classification,Exit_load_Remarks,Fund_Age_Years,Return_1Y_vs_2Y,Return_2Y_vs_3Y,Return_1Y_vs_3Y,Return_3Y_vs_5Y,Avg_Return,NAV_Range_%
0,360 ONE Balanced Hybrid Fund-Reg(G),Mayur Patel,HY-EQ,None,860.1,1.94,Open Ended,2023-09-25,NIFTY 50 Hybrid Composite Debt 50:50 Index,12.45,...,7.5,Hybrid : Equity Oriented,Nil upto 10% of units and 1% for remaining uni...,2.06,NaN,NaN,NaN,NaN,16.18,18.36
1,360 ONE Dynamic Bond Fund-Reg(G),Milan Mody,DT-DYN,2,737.5,0.52,Open Ended,2013-06-24,CRISIL Dynamic Bond Index,21.50,...,1.45,Debt : Dynamic Bond,Nil,12.32,1.18,1.23,1.46,0.99,7.57,9.64
2,360 ONE ELSS Tax Saver Nifty 50 Index Fund-Reg(G),Parijat Garg,EQ-ELSS,None,75.8,0.52,Open Ended,2022-12-28,NIFTY 50 - TRI,13.45,...,13.9,Equity : Tax Saving (ELSS),Nil,2.80,0.63,NaN,NaN,NaN,12.84,24.02
3,360 ONE Flexicap Fund-Reg(G),Mayur Patel,EQ-FLEX,None,1254.2,2.08,Open Ended,2023-06-30,BSE 500 - TRI,15.33,...,15.45,Equity : Flexi Cap,1% on or before 365D Nil after 365D,2.30,NaN,NaN,NaN,NaN,27.02,36.21
4,360 ONE Focused Equity Fund-Reg(G),Mayur Patel,EQ-MLC,4,7305.0,1.78,Open Ended,2014-10-30,BSE 500 - TRI,46.19,...,16.03,Equity : Multi Cap,1% on or before 12M,10.97,0.66,1.57,1.03,0.72,17.61,28.79

- When you invest in a mutual fund, the fund company charges an Expense Ratio (management fees, admin charges, distribution costs, etc.).
- Expense Ratio = % of fund assets deducted every year.
- Expense Impact = the effect of this deduction on your returns over time.
- It directly reduces your Net Asset Value (NAV) and hence your gains.

In [116]:
df_2["Expense_vs_Return_1Y"] = round((df_2["Expense_Ratio"]/df_2["Return_1Y"]),2)

In [117]:
df_2["AUM_Category"] = pd.cut(
    df_1["AUM_Cr"],
    bins=[0, 500, 5000, 20000, 100000, float("inf")],
    labels=["Small", "Mid", "Large", "Mega", "Giant"]
)

In [118]:
df_2["AUM_Category"]

0         Mid
1         Mid
2       Small
3         Mid
4       Large
        ...
1792    Small
1793    Small
1794    Small
1795      Mid
1796    Small
Name: AUM_Category, Length: 1797, dtype: category
Categories (5, object): ['Small' < 'Mid' < 'Large' < 'Mega' < 'Giant']

In [119]:
# 3-Year Return is Standard in Mutual Fund Analysis
# 1-year return â†’ too short-term, can be highly volatile and influenced by market noise.
# 5- or 10-year return â†’ too long-term, may not reflect the fund managerâ€™s recent performance or expense impact.
# 3-year return â†’ gives a medium-term perspective: balances stability and relevance.

In [120]:
df_2["Return_to_Expense"] = (df_2["Return_3Y"] / df_2["Expense_Ratio"]).round(2)

In [121]:
df_2[["Fund_Age_Years", "Avg_Return", "NAV_Range_%", "AUM_Category", "Return_to_Expense"]].head()

   Fund_Age_Years  Avg_Return  NAV_Range_% AUM_Category  Return_to_Expense
0            2.06       16.18        18.36          Mid                NaN
1           12.32        7.57         9.64          Mid              12.69
2            2.80       12.84        24.02        Small                NaN
3            2.30       27.02        36.21          Mid                NaN
4           10.97       17.61        28.79        Large               8.15

In [122]:

cat_cols = [
    "Funds", "Fund_Manager", "Category", "Fund_Type",
    "Benchmark_Index", "Highest_Sector", "classification",
    "RupeeVestRating", "AUM_Category"
]

for col in cat_cols:
    df_2[col] = (
        df_2[col]
        .astype(str)
        .str.strip()
        .str.replace("-", " ", regex=True)
        .str.replace("_", " ", regex=True)
        .str.replace(":", " - ", regex=True)
        .str.replace(r"\s+", " ", regex=True)   
        .str.title()                            
        .replace(
            ["Nan", "Na", "None", "Not Rated", "Nr", "Unrated", "Null", ""],
            pd.NA
        )
    )

df_2["Category"] = df_2["Category"].fillna("Unknown")
df_2["Fund_Type"] = df_2["Fund_Type"].fillna("Unknown")
df_2["AUM_Category"] = df_2["AUM_Category"].fillna("Unknown")

df_2[cat_cols].head()

,Funds,Fund_Manager,Category,Fund_Type,Benchmark_Index,Highest_Sector,classification,RupeeVestRating,AUM_Category
0,360 One Balanced Hybrid Fund Reg(G),Mayur Patel,Hy Eq,Open Ended,Nifty 50 Hybrid Composite Debt 50 - 50 Index,Financials,Hybrid - Equity Oriented,<NA>,Mid
1,360 One Dynamic Bond Fund Reg(G),Milan Mody,Dt Dyn,Open Ended,Crisil Dynamic Bond Index,,Debt - Dynamic Bond,2,Mid
2,360 One Elss Tax Saver Nifty 50 Index Fund Reg(G),Parijat Garg,Eq Elss,Open Ended,Nifty 50 Tri,Financials,Equity - Tax Saving (Elss),<NA>,Small
3,360 One Flexicap Fund Reg(G),Mayur Patel,Eq Flex,Open Ended,Bse 500 Tri,Financials,Equity - Flexi Cap,<NA>,Mid
4,360 One Focused Equity Fund Reg(G),Mayur Patel,Eq Mlc,Open Ended,Bse 500 Tri,Financials,Equity - Multi Cap,4,Large

In [123]:

df_2["Fund_Age_Years"] = (
    (pd.Timestamp.today() - pd.to_datetime(df_2["Inception_Date"], errors="coerce")).dt.days / 365
).round(2)

df_2["NAV_Range_%"] = (
    ((df_2["52_WeekHigh_NAV"] - df_2["52_WeekLow_NAV"]) / df_2["52_WeekLow_NAV"]) * 100
).round(2)

df_2["Return_1Y_vs_2Y"] = (df_2["Return_1Y"] - df_2["Return_2Y"]).round(2)
df_2["Return_2Y_vs_3Y"] = (df_2["Return_2Y"] - df_2["Return_3Y"]).round(2)
df_2["Return_1Y_vs_3Y"] = (df_2["Return_1Y"] - df_2["Return_3Y"]).round(2)
df_2["Return_3Y_vs_5Y"] = (df_2["Return_3Y"] - df_2["Return_5Y"]).round(2)

return_cols = ["Return_1Y", "Return_3Y", "Return_5Y", "Return_10Y"]
df_2["Avg_Return"] = df_2[return_cols].mean(axis=1).round(2)

df_2["Expense_vs_Return_1Y"] = (
    (df_2["Expense_Ratio"] / df_2["Return_1Y"])
).replace([np.inf, -np.inf], np.nan).round(2)

df_2["Return_to_Expense"] = (
    df_2["Return_1Y"] / df_2["Expense_Ratio"]
).replace([np.inf, -np.inf], np.nan).round(2)

df_2["AUM_Category"] = pd.cut(
    df_2["AUM_Cr"],
    bins=[0, 100, 500, 2000, np.inf],
    labels=["Small", "Mid", "Large", "Mega"]
)

df_2[[
    "Funds", "Fund_Age_Years", "NAV_Range_%", "Return_1Y_vs_2Y",
    "Avg_Return", "Expense_vs_Return_1Y", "Return_to_Expense", "AUM_Category"
]].head()

,Funds,Fund_Age_Years,NAV_Range_%,Return_1Y_vs_2Y,Avg_Return,Expense_vs_Return_1Y,Return_to_Expense,AUM_Category
0,360 One Balanced Hybrid Fund Reg(G),2.06,18.36,NaN,16.18,0.12,8.34,Large
1,360 One Dynamic Bond Fund Reg(G),12.32,9.64,1.49,7.44,0.05,18.50,Large
2,360 One Elss Tax Saver Nifty 50 Index Fund Reg(G),2.80,24.02,-5.87,9.91,0.05,19.06,Small
3,360 One Flexicap Fund Reg(G),2.30,36.21,NaN,27.02,0.08,12.99,Large
4,360 One Focused Equity Fund Reg(G),10.97,28.79,-7.81,16.33,0.12,8.37,Mega

In [124]:

df_3 = df_2.copy()

risk_cols = ["Alpha", "Beta", "Sharpe", "Sortino", "Standard_Deviation"]
for col in risk_cols:
    df_3[col] = pd.to_numeric(df_3[col], errors="coerce")

df_3["Risk_Category"] = pd.cut(
    df_3["Standard_Deviation"],
    bins=[-np.inf, 10, 20, np.inf],
    labels=["Low", "Medium", "High"]
)

df_3["Return_to_Risk"] = (df_3["Avg_Return"] / df_3["Standard_Deviation"]).replace([np.inf, -np.inf], np.nan).round(2)

df_3["Positive_Alpha_Beta_Less1"] = ((df_3["Alpha"] > 0) & (df_3["Beta"] < 1))

df_3["Risk_Adjusted_Performance"] = df_3[["Sharpe", "Sortino"]].mean(axis=1).round(2)

df_3["High_Expense_Low_Return"] = ((df_3["Expense_Ratio"] > df_3["Return_1Y"])).astype(int)

df_3[[
    "Funds", "Risk_Category", "Return_to_Risk", 
    "Positive_Alpha_Beta_Less1", "Risk_Adjusted_Performance", 
    "High_Expense_Low_Return"
]].head(10)

,Funds,Risk_Category,Return_to_Risk,Positive_Alpha_Beta_Less1,Risk_Adjusted_Performance,High_Expense_Low_Return
0,360 One Balanced Hybrid Fund Reg(G),Low,2.16,False,1.93,0
1,360 One Dynamic Bond Fund Reg(G),Low,5.13,True,5.21,0
2,360 One Elss Tax Saver Nifty 50 Index Fund Reg(G),Medium,0.71,True,0.59,0
3,360 One Flexicap Fund Reg(G),Medium,1.75,True,1.71,0
4,360 One Focused Equity Fund Reg(G),Medium,1.02,False,0.86,0
5,360 One Liquid Fund Reg(G),Low,38.12,False,11.60,0
6,360 One Quant Fund Reg(G),Medium,1.16,False,1.16,0
7,Aditya Birla Sl Active Debt Multi Mgr Fof(G),Low,3.83,True,2.97,0
8,Aditya Birla Sl Arbitrage Fund(G),Low,6.27,True,5.36,0
9,Aditya Birla Sl Asset Allocator Fof(G),Medium,1.24,False,1.32,0

In [125]:

df_3["High_Expense_Low_Return"] = (df_3["Expense_Ratio"] > df_3["Return_1Y"]).astype(int)

df_3["High_NAV_Volatility"] = (df_3["NAV_Range_%"] > 20).astype(int)

avg_return = df_3["Avg_Return"].mean()
df_3["Top_Performer"] = (df_3["Avg_Return"] > avg_return).astype(int)

df_3["Young_Fund"] = (df_3["Fund_Age_Years"] < 5).astype(int)

df_3["Efficient_Fund"] = (df_3["Return_to_Expense"] > 5).astype(int)

final_cols = [
    "Funds", "Fund_Manager", "Fund_Age_Years", "NAV_Range_%", "Avg_Return",
    "Expense_Ratio", "Return_to_Expense", "High_Expense_Low_Return",
    "High_NAV_Volatility", "Top_Performer", "Young_Fund", "Efficient_Fund"
]

df_3_final = df_3[final_cols]

df_3_final.head()

,Funds,Fund_Manager,Fund_Age_Years,NAV_Range_%,Avg_Return,Expense_Ratio,Return_to_Expense,High_Expense_Low_Return,High_NAV_Volatility,Top_Performer,Young_Fund,Efficient_Fund
0,360 One Balanced Hybrid Fund Reg(G),Mayur Patel,2.06,18.36,16.18,1.94,8.34,0,0,1,1,1
1,360 One Dynamic Bond Fund Reg(G),Milan Mody,12.32,9.64,7.44,0.52,18.50,0,0,0,0,1
2,360 One Elss Tax Saver Nifty 50 Index Fund Reg(G),Parijat Garg,2.80,24.02,9.91,0.52,19.06,0,1,0,1,1
3,360 One Flexicap Fund Reg(G),Mayur Patel,2.30,36.21,27.02,2.08,12.99,0,1,1,1,1
4,360 One Focused Equity Fund Reg(G),Mayur Patel,10.97,28.79,16.33,1.78,8.37,0,1,1,0,1

In [126]:
import numpy as np
import pandas as pd

df_3["Inception_Date"] = pd.to_datetime(df_3["Inception_Date"], errors="coerce")

df_3["ShortTerm_Return"] = df_3[["Return_1M", "Return_3M", "Return_6M"]].mean(axis=1).round(2)

df_3["LongTerm_Return"] = df_3[["Return_3Y", "Return_5Y", "Return_10Y"]].mean(axis=1).round(2)

df_3["Risk_Category"] = pd.cut(
    df_3["Standard_Deviation"],
    bins=[-np.inf, 5, 15, np.inf],
    labels=["Low", "Medium", "High"]
)

df_3["Return_to_Risk"] = (df_3["Return_3Y"] / df_3["Standard_Deviation"]).replace([np.inf, -np.inf], np.nan).round(2)

fund_overview = df_3[["Funds", "Fund_Manager", "Category", "AUM_Cr", "Expense_Ratio"]]

performance_metrics = df_3[[
    "Funds", "Return_1M", "Return_3M", "Return_6M", "Return_1Y",
    "Return_2Y", "Return_3Y", "Return_5Y", "Return_10Y", "Alpha", "Beta", "Sharpe"
]]

risk_profile = df_3[[
    "Funds", "Standard_Deviation", "Turnover_Ratio_", "Avg_MarketCap_Cr", "Large_Cap", "Mid_Cap", "Small_Cap"
]]

portfolio_allocation = df_3[[
    "Funds", "Large_Cap", "Mid_Cap", "Small_Cap", "Highest_Sector"
]]

df_3.head()

,Funds,Fund_Manager,Category,RupeeVestRating,AUM_Cr,Expense_Ratio,Fund_Type,Inception_Date,Benchmark_Index,NAV,...,Return_to_Risk,Positive_Alpha_Beta_Less1,Risk_Adjusted_Performance,High_Expense_Low_Return,High_NAV_Volatility,Top_Performer,Young_Fund,Efficient_Fund,ShortTerm_Return,LongTerm_Return
0,360 One Balanced Hybrid Fund Reg(G),Mayur Patel,Hy Eq,<NA>,860.1,1.94,Open Ended,2023-09-25,Nifty 50 Hybrid Composite Debt 50 - 50 Index,12.45,...,NaN,False,1.93,0,0,1,1,1,0.16,NaN
1,360 One Dynamic Bond Fund Reg(G),Milan Mody,Dt Dyn,2,737.5,0.52,Open Ended,2013-06-24,Crisil Dynamic Bond Index,21.50,...,4.55,True,5.21,0,0,0,0,1,2.15,6.71
2,360 One Elss Tax Saver Nifty 50 Index Fund Reg(G),Parijat Garg,Eq Elss,<NA>,75.8,0.52,Open Ended,2022-12-28,Nifty 50 Tri,13.45,...,NaN,True,0.59,0,1,0,1,1,-3.64,NaN
3,360 One Flexicap Fund Reg(G),Mayur Patel,Eq Flex,<NA>,1254.2,2.08,Open Ended,2023-06-30,Bse 500 Tri,15.33,...,NaN,True,1.71,0,1,1,1,1,-1.96,NaN
4,360 One Focused Equity Fund Reg(G),Mayur Patel,Eq Mlc,4,7305.0,1.78,Open Ended,2014-10-30,Bse 500 Tri,46.19,...,0.90,False,0.86,0,1,1,0,1,-5.23,16.81

In [127]:
cols_to_drop = [
    "RupeeVestRating", "Exit_load_Remarks", "classification", 
    "No_ofStocks", "Avg_MarketCap_Cr", "Turnover_Ratio_", 
    "Avg_Maturity_Yrs", "Mod_Duration_Yrs", "YTM", 
    "NAV", "52_WeekHigh_NAV", "52_WeekLow_NAV", 
    "Return_1Y_vs_2Y", "Return_2Y_vs_3Y", "Return_1Y_vs_3Y", "Return_3Y_vs_5Y",
    "NAV_Range_%"
]

df_cleaned = df_3.drop(columns=cols_to_drop, errors='ignore')

df_cleaned.to_csv("Mutual_Funds_Visualization_Ready.csv", index=False)

In [130]:
!pip install plotly
!pip install -U nbformat

Requirement already satisfied: plotly in c:\users\sinha\appdata\local\programs\python\python313\lib\site-packages (6.3.1)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\sinha\appdata\local\programs\python\python313\lib\site-packages (from plotly) (2.8.0)
Requirement already satisfied: packaging in c:\users\sinha\appdata\roaming\python\python313\site-packages (from plotly) (25.0)
Collecting nbformat
  Downloading nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting fastjsonschema>=2.15 (from nbformat)
  Downloading fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting jsonschema>=2.6 (from nbformat)
  Downloading jsonschema-4.25.1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\sinha\appdata\roaming\python\python313\site-packages (from nbformat) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\sinha\appdata\roaming\python\python313\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\sinha\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat) (25.3.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=2.6->nbformat)
  Downloading rpds_py-0.27.1-cp313-cp313-win_amd64.whl.metadata (4.3 kB)
Requirement already satisfied: platformdirs>=2.5 in c:\users\sinha\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\sinha\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (311)
Downloading nbformat-5.10.4-py3-none-any.whl (78 kB)
Downloading fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Downloading jsonschema-4.25.1-py3-none-any.whl (90 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-0.27.1-cp313-cp313-win_amd64.whl (232 kB)
Installing collected packages: fastjsonschema, rpds-py, referencing, jsonschema-specifications, jsonschema, nbformat

   ---------------------------------------- 0/6 [fastjsonschema]
   ------------- -------------------------- 2/6 [referencing]
   ------------- -------------------------- 2/6 [referencing]
   -------------------- ------------------- 3/6 [jsonschema-specifications]
   -------------------------- ------------- 4/6 [jsonschema]
   -------------------------- ------------- 4/6 [jsonschema]
   -------------------------- ------------- 4/6 [jsonschema]
   -------------------------- ------------- 4/6 [jsonschema]
   -------------------------- ------------- 4/6 [jsonschema]
   -------------------------- ------------- 4/6 [jsonschema]
   --------------------------------- ------ 5/6 [nbformat]
   --------------------------------- ------ 5/6 [nbformat]
   --------------------------------- ------ 5/6 [nbformat]
   --------------------------------- ------ 5/6 [nbformat]
   --------------------------------- ------ 5/6 [nbformat]
   --------------------------------- ------ 5/6 [nbformat]
   ---------------------------------------- 6/6 [nbformat]

Successfully installed fastjsonschema-2.21.2 jsonschema-4.25.1 jsonschema-specifications-2025.9.1 nbformat-5.10.4 referencing-0.37.0 rpds-py-0.27.1

In [1]:
import plotly.io as pio

pio.renderers.default = 'browser'  # forces it to open in a browser tab

fig1 = px.scatter(
    df_3,
    x="Standard_Deviation",
    y="Avg_Return",
    color="Risk_Category",
    size="AUM_Cr",
    hover_data=["Funds", "Category", "Sharpe", "Return_to_Risk"],
    title="Risk vs Return Comparison of Mutual Funds",
    template="plotly_dark"
)
fig1.show()

NameError: name 'px' is not defined

In [132]:
import plotly.io as pio
pio.renderers.default = 'browser'  # opens chart in a new browser tab

df_category = (
    df_cleaned.groupby("Category")[["Return_1Y", "Return_3Y", "Return_5Y", "Return_10Y"]]
    .mean()
    .reset_index()
)

fig2 = px.line(
    df_category,
    x="Category",
    y=["Return_1Y", "Return_3Y", "Return_5Y", "Return_10Y"],
    markers=True,
    title="Category-wise Average Returns Over Time",
    template="plotly_dark"
)
fig2.show()